language: python
python:
  - 2.7
# prevent travis from doing pip install requirements.txt
install: true
script:
# disable Travis default virtualenv
- deactivate
# deploy dx-toolkit
- wget https://wiki.dnanexus.com/images/files/dx-toolkit-current-ubuntu-12.04-amd64.tar.gz
- tar zxf dx-toolkit-current-ubuntu-12.04-amd64.tar.gz
- source dx-toolkit/environment
# pre-warm later workflow stages
- for i in $(seq 1 3); do dx run --project-context-id project-BXBXK180x0z7x5kxq11p886f /assets/eval -i sh="sleep 1" --name "prewarming no-op" --instance-type mem1_ssd1_x4 --brief -y; done
# execute workflow builder script
- python build_assembly_workflow.py --species Ebola Lassa --run-tests
env:
  global:
  - secure: "hqaflXcPTtAoDDA/KmsTOT8P3tbRQoPLzpzN65UlN0ZlvMM61MjnY0fOQxKNLKrwgQzZWehNt/iXHkEvnYAQopUNlfQ7By5M1njFJSKbdix9UG+B4uF7/ERfxnT+F+AyXiJM974l6uvXAE5s3k7CVTwMol6Rx9XcEA7Sq5sVs/8="
